// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         recipe_id: "recipe_id"
 *     }
 */
export interface FavoriteRecipeRequest {
    recipe_id: string;
    is_favorite?: boolean;
}
