// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ingredients: ["ingredients"]
 *     }
 */
export interface GenerateRecipeRequest {
    ingredients: string[];
    dish_name?: string | null;
    cuisine?: string | null;
    dietary_restrictions?: string | null;
}
