// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface MultimodalRecipeRequest {
    image_url?: string | null;
    media_url?: string | null;
    additional_notes?: string | null;
}
