// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         ingredients: ["ingredients"]
 *     }
 */
export interface SaveRecipeRequest {
    name: string;
    ingredients: string[];
    instructions?: string[] | null;
    servings?: number;
    description?: string | null;
    prep_time_minutes?: number | null;
    cook_time_minutes?: number | null;
    cuisine?: string | null;
    tags?: string[] | null;
    source?: string | null;
    image_url?: string | null;
}
