// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         recipe_json: {
 *             "key": "value"
 *         },
 *         target_servings: 1
 *     }
 */
export interface ScaleRecipeRequest {
    recipe_json: Record<string, unknown>;
    target_servings: number;
}
