// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         raw_text: "raw_text"
 *     }
 */
export interface StandardizeRecipeRequest {
    raw_text: string;
}
