// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         recipe_id: "recipe_id"
 *     }
 */
export interface UpdateRecipeRequest {
    recipe_id: string;
    name?: string | null;
    ingredients?: string[] | null;
    instructions?: string[] | null;
    servings?: number | null;
    description?: string | null;
    prep_time_minutes?: number | null;
    cook_time_minutes?: number | null;
    cuisine?: string | null;
    tags?: string[] | null;
    source?: string | null;
    image_url?: string | null;
}
