// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as FoodContextProtocolApi from "../../../index.js";

export declare namespace MiscClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Miscellaneous utility endpoints
 */
export class MiscClient {
    protected readonly _options: NormalizedClientOptions<MiscClient.Options>;

    constructor(options: MiscClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Enrich a food log entry with AI analysis. Requires authentication.
     *
     * @param {FoodContextProtocolApi.EnrichRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.enrichLog({
     *         log_id: "log_id"
     *     })
     */
    public enrichLog(
        request: FoodContextProtocolApi.EnrichRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__enrichLog(request, requestOptions));
    }

    private async __enrichLog(
        request: FoodContextProtocolApi.EnrichRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "enrich",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/enrich");
    }

    /**
     * Get AI-powered meal suggestions.
     *
     * @param {FoodContextProtocolApi.SuggestRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.mealSuggestions()
     */
    public mealSuggestions(
        request: FoodContextProtocolApi.SuggestRequest = {},
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__mealSuggestions(request, requestOptions));
    }

    private async __mealSuggestions(
        request: FoodContextProtocolApi.SuggestRequest = {},
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "suggest",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/suggest");
    }

    /**
     * Generate a detailed, style-optimized prompt for creating food images.
     *
     * @param {FoodContextProtocolApi.ImagePromptRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.postImagePrompt({
     *         subject: "subject"
     *     })
     */
    public postImagePrompt(
        request: FoodContextProtocolApi.ImagePromptRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postImagePrompt(request, requestOptions));
    }

    private async __postImagePrompt(
        request: FoodContextProtocolApi.ImagePromptRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "visual/image-prompt",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/visual/image-prompt");
    }

    /**
     * Log a meal by providing a URL to an audio recording. Requires authentication.
     *
     * @param {FoodContextProtocolApi.AudioLogRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.postAudioLog({
     *         audio_url: "audio_url"
     *     })
     */
    public postAudioLog(
        request: FoodContextProtocolApi.AudioLogRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postAudioLog(request, requestOptions));
    }

    private async __postAudioLog(
        request: FoodContextProtocolApi.AudioLogRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "audio/log-meal",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/audio/log-meal");
    }

    /**
     * Extract user's intent to correct a food log entry from voice input.
     *
     * @param {FoodContextProtocolApi.VoiceCorrectionRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.postVoiceCorrection({
     *         voice_input: "voice_input"
     *     })
     */
    public postVoiceCorrection(
        request: FoodContextProtocolApi.VoiceCorrectionRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postVoiceCorrection(request, requestOptions));
    }

    private async __postVoiceCorrection(
        request: FoodContextProtocolApi.VoiceCorrectionRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "audio/voice-correction",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/audio/voice-correction");
    }

    /**
     * Analyze a voice transcript to extract meal information for log creation.
     *
     * @param {FoodContextProtocolApi.VoiceTranscriptRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.postAnalyzeVoice({
     *         transcript: "transcript"
     *     })
     */
    public postAnalyzeVoice(
        request: FoodContextProtocolApi.VoiceTranscriptRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postAnalyzeVoice(request, requestOptions));
    }

    private async __postAnalyzeVoice(
        request: FoodContextProtocolApi.VoiceTranscriptRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "analyze/voice",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/analyze/voice");
    }

    /**
     * Generate a legally compliant food label for home-based businesses.
     *
     * @param {FoodContextProtocolApi.CottageLabelRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.postCottageLabel({
     *         product_name: "product_name",
     *         ingredients: ["ingredients"]
     *     })
     */
    public postCottageLabel(
        request: FoodContextProtocolApi.CottageLabelRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postCottageLabel(request, requestOptions));
    }

    private async __postCottageLabel(
        request: FoodContextProtocolApi.CottageLabelRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "cottage/label",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/cottage/label");
    }

    /**
     * Analyze recent food logs and generate a professional clinical report.
     *
     * @param {FoodContextProtocolApi.GetClinicalReportClinicalReportGetRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.getClinicalReport()
     */
    public getClinicalReport(
        request: FoodContextProtocolApi.GetClinicalReportClinicalReportGetRequest = {},
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getClinicalReport(request, requestOptions));
    }

    private async __getClinicalReport(
        request: FoodContextProtocolApi.GetClinicalReportClinicalReportGetRequest = {},
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { days, focus_area: focusArea } = request;
        const _queryParams: Record<string, unknown> = {
            days,
            focus_area: focusArea,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "clinical/report",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/clinical/report");
    }

    /**
     * Plan a community food festival based on local engagement.
     *
     * @param {FoodContextProtocolApi.FoodFestivalRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.postPlanFestival({
     *         city_name: "city_name",
     *         theme: "theme"
     *     })
     */
    public postPlanFestival(
        request: FoodContextProtocolApi.FoodFestivalRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postPlanFestival(request, requestOptions));
    }

    private async __postPlanFestival(
        request: FoodContextProtocolApi.FoodFestivalRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "civic/plan-festival",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/civic/plan-festival");
    }

    /**
     * Identify culinary gaps in a neighborhood.
     *
     * @param {FoodContextProtocolApi.EconomicGapRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.postEconomicGaps({
     *         neighborhood: "neighborhood",
     *         existing_cuisines: ["existing_cuisines"]
     *     })
     */
    public postEconomicGaps(
        request: FoodContextProtocolApi.EconomicGapRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postEconomicGaps(request, requestOptions));
    }

    private async __postEconomicGaps(
        request: FoodContextProtocolApi.EconomicGapRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "civic/economic-gaps",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/civic/economic-gaps");
    }

    /**
     * Parse a restaurant menu image into structured dish data.
     *
     * @param {FoodContextProtocolApi.ImageUrlRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.postParseMenu({
     *         image_url: "image_url"
     *     })
     */
    public postParseMenu(
        request: FoodContextProtocolApi.ImageUrlRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postParseMenu(request, requestOptions));
    }

    private async __postParseMenu(
        request: FoodContextProtocolApi.ImageUrlRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "parser/menu",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/parser/menu");
    }

    /**
     * Parse a grocery receipt image into itemized pantry data.
     *
     * @param {FoodContextProtocolApi.ImageUrlRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.postParseReceipt({
     *         image_url: "image_url"
     *     })
     */
    public postParseReceipt(
        request: FoodContextProtocolApi.ImageUrlRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postParseReceipt(request, requestOptions));
    }

    private async __postParseReceipt(
        request: FoodContextProtocolApi.ImageUrlRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "parser/receipt",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/parser/receipt");
    }

    /**
     * Check a dish against user allergies and dietary preferences.
     *
     * @param {FoodContextProtocolApi.DietaryCheckRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.postDietaryCheck({
     *         dish_name: "dish_name",
     *         ingredients: ["ingredients"],
     *         user_allergies: ["user_allergies"],
     *         user_diet: ["user_diet"]
     *     })
     */
    public postDietaryCheck(
        request: FoodContextProtocolApi.DietaryCheckRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postDietaryCheck(request, requestOptions));
    }

    private async __postDietaryCheck(
        request: FoodContextProtocolApi.DietaryCheckRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "taste-buddy/check",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/taste-buddy/check");
    }

    /**
     * Get perfect culinary pairings for an ingredient or dish.
     *
     * @param {FoodContextProtocolApi.GetPairingsFlavorPairingsGetRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.getPairings({
     *         subject: "subject"
     *     })
     */
    public getPairings(
        request: FoodContextProtocolApi.GetPairingsFlavorPairingsGetRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getPairings(request, requestOptions));
    }

    private async __getPairings(
        request: FoodContextProtocolApi.GetPairingsFlavorPairingsGetRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { subject, pairing_type: pairingType } = request;
        const _queryParams: Record<string, unknown> = {
            subject,
            pairing_type: pairingType,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "flavor/pairings",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/flavor/pairings");
    }

    /**
     * Identify trending food movements based on global and local data.
     *
     * @param {FoodContextProtocolApi.GetTrendsTrendsIdentifyGetRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.getTrends()
     */
    public getTrends(
        request: FoodContextProtocolApi.GetTrendsTrendsIdentifyGetRequest = {},
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getTrends(request, requestOptions));
    }

    private async __getTrends(
        request: FoodContextProtocolApi.GetTrendsTrendsIdentifyGetRequest = {},
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { region, cuisine_focus: cuisineFocus } = request;
        const _queryParams: Record<string, unknown> = {
            region,
            cuisine_focus: cuisineFocus,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "trends/identify",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/trends/identify");
    }

    /**
     * Pledge a meal for donation to a food program. Requires authentication.
     *
     * This marks the meal as donated and associates it with a food bank or
     * community organization for social impact tracking.
     *
     * @param {FoodContextProtocolApi.DonateMealRequest} request
     * @param {MiscClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.misc.postDonateMeal({
     *         log_id: "log_id"
     *     })
     */
    public postDonateMeal(
        request: FoodContextProtocolApi.DonateMealRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postDonateMeal(request, requestOptions));
    }

    private async __postDonateMeal(
        request: FoodContextProtocolApi.DonateMealRequest,
        requestOptions?: MiscClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "impact/donate",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/impact/donate");
    }
}
