// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as FoodContextProtocolApi from "../../../index.js";

export declare namespace ResearchClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Deep research reports using AI
 */
export class ResearchClient {
    protected readonly _options: NormalizedClientOptions<ResearchClient.Options>;

    constructor(options: ResearchClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Generate a comprehensive research report on a food-related topic.
     *
     * Uses the Deep Research Agent which autonomously:
     * - Plans research approach
     * - Executes multiple search queries
     * - Synthesizes findings into a report
     *
     * **Note**: This is a long-running operation (typically 3-5+ minutes).
     *
     * **Examples**:
     * - "Mediterranean diet health benefits"
     * - "Best cooking methods for nutrient retention"
     * - "Food trends in plant-based proteins"
     *
     * @param {FoodContextProtocolApi.ResearchRequest} request
     * @param {ResearchClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.research.research({
     *         topic: "topic"
     *     })
     */
    public research(
        request: FoodContextProtocolApi.ResearchRequest,
        requestOptions?: ResearchClient.RequestOptions,
    ): core.HttpResponsePromise<FoodContextProtocolApi.ResearchResponse> {
        return core.HttpResponsePromise.fromPromise(this.__research(request, requestOptions));
    }

    private async __research(
        request: FoodContextProtocolApi.ResearchRequest,
        requestOptions?: ResearchClient.RequestOptions,
    ): Promise<core.WithRawResponse<FoodContextProtocolApi.ResearchResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "research",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as FoodContextProtocolApi.ResearchResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/research");
    }
}
