// This file was auto-generated by Fern from our API Definition.

import { AgentsClient } from "./api/resources/agents/client/Client.js";
import { AnalyticsClient } from "./api/resources/analytics/client/Client.js";
import { AnalyzeClient } from "./api/resources/analyze/client/Client.js";
import { ConnectorsClient } from "./api/resources/connectors/client/Client.js";
import { DiscoveryClient } from "./api/resources/discovery/client/Client.js";
import { ExternalClient } from "./api/resources/external/client/Client.js";
import { HealthClient } from "./api/resources/health/client/Client.js";
import { InventoryClient } from "./api/resources/inventory/client/Client.js";
import { KnowledgeClient } from "./api/resources/knowledge/client/Client.js";
import { MealsClient } from "./api/resources/meals/client/Client.js";
import { MiscClient } from "./api/resources/misc/client/Client.js";
import { ParserClient } from "./api/resources/parser/client/Client.js";
import { ProfileClient } from "./api/resources/profile/client/Client.js";
import { PublishingClient } from "./api/resources/publishing/client/Client.js";
import { RecipesClient } from "./api/resources/recipes/client/Client.js";
import { ResearchClient } from "./api/resources/research/client/Client.js";
import { SafetyClient } from "./api/resources/safety/client/Client.js";
import { SchedulerClient } from "./api/resources/scheduler/client/Client.js";
import { SearchClient } from "./api/resources/search/client/Client.js";
import { SocialClient } from "./api/resources/social/client/Client.js";
import { VideoClient } from "./api/resources/video/client/Client.js";
import { VoiceClient } from "./api/resources/voice/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";
import { handleNonStatusCodeError } from "./errors/handleNonStatusCodeError.js";
import * as errors from "./errors/index.js";

export declare namespace FoodContextProtocolApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FoodContextProtocolApiClient {
    protected readonly _options: NormalizedClientOptions<FoodContextProtocolApiClient.Options>;
    protected _meals: MealsClient | undefined;
    protected _search: SearchClient | undefined;
    protected _safety: SafetyClient | undefined;
    protected _profile: ProfileClient | undefined;
    protected _publishing: PublishingClient | undefined;
    protected _analyze: AnalyzeClient | undefined;
    protected _analytics: AnalyticsClient | undefined;
    protected _agents: AgentsClient | undefined;
    protected _inventory: InventoryClient | undefined;
    protected _knowledge: KnowledgeClient | undefined;
    protected _discovery: DiscoveryClient | undefined;
    protected _recipes: RecipesClient | undefined;
    protected _social: SocialClient | undefined;
    protected _connectors: ConnectorsClient | undefined;
    protected _external: ExternalClient | undefined;
    protected _scheduler: SchedulerClient | undefined;
    protected _parser: ParserClient | undefined;
    protected _misc: MiscClient | undefined;
    protected _research: ResearchClient | undefined;
    protected _video: VideoClient | undefined;
    protected _voice: VoiceClient | undefined;
    protected _health: HealthClient | undefined;

    constructor(options: FoodContextProtocolApiClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get meals(): MealsClient {
        return (this._meals ??= new MealsClient(this._options));
    }

    public get search(): SearchClient {
        return (this._search ??= new SearchClient(this._options));
    }

    public get safety(): SafetyClient {
        return (this._safety ??= new SafetyClient(this._options));
    }

    public get profile(): ProfileClient {
        return (this._profile ??= new ProfileClient(this._options));
    }

    public get publishing(): PublishingClient {
        return (this._publishing ??= new PublishingClient(this._options));
    }

    public get analyze(): AnalyzeClient {
        return (this._analyze ??= new AnalyzeClient(this._options));
    }

    public get analytics(): AnalyticsClient {
        return (this._analytics ??= new AnalyticsClient(this._options));
    }

    public get agents(): AgentsClient {
        return (this._agents ??= new AgentsClient(this._options));
    }

    public get inventory(): InventoryClient {
        return (this._inventory ??= new InventoryClient(this._options));
    }

    public get knowledge(): KnowledgeClient {
        return (this._knowledge ??= new KnowledgeClient(this._options));
    }

    public get discovery(): DiscoveryClient {
        return (this._discovery ??= new DiscoveryClient(this._options));
    }

    public get recipes(): RecipesClient {
        return (this._recipes ??= new RecipesClient(this._options));
    }

    public get social(): SocialClient {
        return (this._social ??= new SocialClient(this._options));
    }

    public get connectors(): ConnectorsClient {
        return (this._connectors ??= new ConnectorsClient(this._options));
    }

    public get external(): ExternalClient {
        return (this._external ??= new ExternalClient(this._options));
    }

    public get scheduler(): SchedulerClient {
        return (this._scheduler ??= new SchedulerClient(this._options));
    }

    public get parser(): ParserClient {
        return (this._parser ??= new ParserClient(this._options));
    }

    public get misc(): MiscClient {
        return (this._misc ??= new MiscClient(this._options));
    }

    public get research(): ResearchClient {
        return (this._research ??= new ResearchClient(this._options));
    }

    public get video(): VideoClient {
        return (this._video ??= new VideoClient(this._options));
    }

    public get voice(): VoiceClient {
        return (this._voice ??= new VoiceClient(this._options));
    }

    public get health(): HealthClient {
        return (this._health ??= new HealthClient(this._options));
    }

    /**
     * Health check.
     *
     * @param {FoodContextProtocolApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.rootGet()
     */
    public rootGet(requestOptions?: FoodContextProtocolApiClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__rootGet(requestOptions));
    }

    private async __rootGet(
        requestOptions?: FoodContextProtocolApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url:
                (await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FoodContextProtocolApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/");
    }
}
