// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         agent_name: "agent_name",
 *         objective: "objective"
 *     }
 */
export interface DelegateAgentRequest {
    agent_name: string;
    objective: string;
}
