// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface DiscoveryRequest {
    location?: string | null;
    discovery_type?: string;
    count?: number;
}
