// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         log_ids: ["log_ids"]
 *     }
 */
export interface FoodStoryRequest {
    log_ids: string[];
    theme?: string | null;
}
