// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         streak_days: 1
 *     }
 */
export interface GetStreakCelebrationAgentsStreakStreakDaysGetRequest {
    streak_days: number;
    user_name?: string | null;
}
