// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         image_urls: ["image_urls"]
 *     }
 */
export interface MediaBatchRequest {
    image_urls: string[];
    auto_log?: boolean;
}
