// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface RecipeDiscoveryRequest {
    available_ingredients?: string[] | null;
    dietary_restrictions?: string[] | null;
}
