// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         log_id: "log_id"
 *     }
 */
export interface RecipeCardRequest {
    log_id: string;
    include_instructions?: boolean;
}
