// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         log_id: "log_id"
 *     }
 */
export interface SocialPostRequest {
    log_id: string;
    platform?: string;
    style?: string;
}
