// This file was auto-generated by Fern from our API Definition.

import type * as FoodContextProtocolApi from "../index.js";

export interface HttpValidationError {
    detail?: FoodContextProtocolApi.ValidationError[];
}
