// This file was auto-generated by Fern from our API Definition.

/**
 * Request body for recipe video generation.
 */
export interface RecipeVideoRequest {
    /** Name of the dish */
    dish_name: string;
    /** Additional context or specific shots desired */
    description?: string | null;
    /** Video style: cinematic, tutorial, social, lifestyle */
    style?: string;
    /** Video length (4-8 seconds) */
    duration_seconds?: number;
    /** Aspect ratio: 16:9 (landscape) or 9:16 (portrait) */
    aspect_ratio?: string;
    /** Max wait time in seconds */
    timeout_seconds?: number;
}
