// This file was auto-generated by Fern from our API Definition.

/**
 * Response from research endpoint.
 */
export interface ResearchResponse {
    /** Status: completed, failed, or timeout */
    status: string;
    /** The research report (if completed) */
    report?: string | null;
    /** Original research topic */
    topic: string;
    /** ID for follow-up queries */
    interaction_id?: string | null;
    /** Error or status message */
    message?: string | null;
}
