// This file was auto-generated by Fern from our API Definition.

/**
 * Response from video generation endpoint.
 */
export interface VideoResponse {
    /** Status: completed, timeout, or failed */
    status: string;
    /** Base64-encoded video data */
    video_base64?: string | null;
    /** Video duration in seconds */
    duration?: number | null;
    /** Dish name (for recipe videos) */
    dish_name?: string | null;
    /** Cooking action (for clips) */
    action?: string | null;
    /** Video style used */
    style?: string | null;
    /** Operation ID for status checks */
    operation_name?: string | null;
    /** Error or status message */
    message?: string | null;
}
