// This file was auto-generated by Fern from our API Definition.

/**
 * Response from voice meal logging.
 */
export interface VoiceMealLogResponse {
    /** Status: logged, clarification_needed, or error */
    status: string;
    /** Extracted meal information (if logged) */
    meal_data?: Record<string, unknown> | null;
    /** AI's text response */
    response_text?: string | null;
    /** AI's audio response (base64) */
    response_audio_base64?: string | null;
    /** Error message if status is error */
    error?: string | null;
}
