// This file was auto-generated by Fern from our API Definition.

/**
 * Response from voice food query.
 */
export interface VoiceFoodQueryResponse {
    /** Status: search_requested, response, or error */
    status: string;
    /** Extracted search query (if search requested) */
    query?: string | null;
    /** User ID for context */
    user_id: string;
    /** AI's text response */
    response_text?: string | null;
    /** AI's audio response (base64) */
    response_audio_base64?: string | null;
    /** Error message if status is error */
    error?: string | null;
}
