// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         dish_name: "dish_name"
 *     }
 */
export interface AddMealRequest {
    dish_name: string;
    venue?: string | null;
    notes?: string | null;
    image_path?: string | null;
}
