// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         image: fs.createReadStream("/path/to/your/file")
 *     }
 */
export interface BodyCreateMealWithImageMealsWithImagePost {
    image: core.file.Uploadable;
    dish_name?: string | null;
    venue?: string | null;
    notes?: string | null;
    auto_analyze?: boolean;
}
