// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListMealsMealsGetRequest {
    limit?: number;
    days?: number | null;
    include_nutrition?: boolean;
}
