// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         log_id: "log_id"
 *     }
 */
export interface UpdateMealRequest {
    log_id: string;
    dish_name?: string | null;
    venue_name?: string | null;
    notes?: string | null;
    rating?: number | null;
    tags?: string[] | null;
    public?: boolean | null;
    image_path?: string | null;
}
