// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as FoodContextProtocolApi from "../../../index.js";

export declare namespace AgentsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Autonomous AI agents
 */
export class AgentsClient {
    protected readonly _options: NormalizedClientOptions<AgentsClient.Options>;

    constructor(options: AgentsClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Handoff a complex food-related task to a specialized agent.
     *
     * @param {FoodContextProtocolApi.DelegateAgentRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.postDelegateToAgent({
     *         agent_name: "agent_name",
     *         objective: "objective"
     *     })
     */
    public postDelegateToAgent(
        request: FoodContextProtocolApi.DelegateAgentRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postDelegateToAgent(request, requestOptions));
    }

    private async __postDelegateToAgent(
        request: FoodContextProtocolApi.DelegateAgentRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/delegate",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/agents/delegate");
    }

    /**
     * Run autonomous food discovery agent.
     *
     * Combines:
     * - Google Search grounding for real-time data
     * - Extended thinking for preference matching
     * - Function calling for structured recommendations
     *
     * @param {FoodContextProtocolApi.DiscoveryRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.runFoodDiscovery()
     */
    public runFoodDiscovery(
        request: FoodContextProtocolApi.DiscoveryRequest = {},
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__runFoodDiscovery(request, requestOptions));
    }

    private async __runFoodDiscovery(
        request: FoodContextProtocolApi.DiscoveryRequest = {},
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/discover",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/agents/discover");
    }

    /**
     * Discover new restaurants matching user preferences.
     *
     * @param {FoodContextProtocolApi.RestaurantDiscoveryRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.discoverRestaurants({
     *         location: "location"
     *     })
     */
    public discoverRestaurants(
        request: FoodContextProtocolApi.RestaurantDiscoveryRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__discoverRestaurants(request, requestOptions));
    }

    private async __discoverRestaurants(
        request: FoodContextProtocolApi.RestaurantDiscoveryRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/discover/restaurants",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/agents/discover/restaurants");
    }

    /**
     * Discover new recipes based on preferences and available ingredients.
     *
     * @param {FoodContextProtocolApi.RecipeDiscoveryRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.discoverRecipes()
     */
    public discoverRecipes(
        request: FoodContextProtocolApi.RecipeDiscoveryRequest = {},
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__discoverRecipes(request, requestOptions));
    }

    private async __discoverRecipes(
        request: FoodContextProtocolApi.RecipeDiscoveryRequest = {},
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/discover/recipes",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/agents/discover/recipes");
    }

    /**
     * Get today's personalized food insight.
     *
     * Uses grounding for timely, relevant content:
     * - What's in season
     * - Food holidays
     * - Weather-appropriate suggestions
     *
     * @param {FoodContextProtocolApi.GetDailyInsightAgentsDailyInsightGetRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.getDailyInsight()
     */
    public getDailyInsight(
        request: FoodContextProtocolApi.GetDailyInsightAgentsDailyInsightGetRequest = {},
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getDailyInsight(request, requestOptions));
    }

    private async __getDailyInsight(
        request: FoodContextProtocolApi.GetDailyInsightAgentsDailyInsightGetRequest = {},
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { location } = request;
        const _queryParams: Record<string, unknown> = {
            location,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/daily-insight",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/agents/daily-insight");
    }

    /**
     * Generate a celebration message for a logging streak.
     *
     * @param {FoodContextProtocolApi.GetStreakCelebrationAgentsStreakStreakDaysGetRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.getStreakCelebration({
     *         streak_days: 1
     *     })
     */
    public getStreakCelebration(
        request: FoodContextProtocolApi.GetStreakCelebrationAgentsStreakStreakDaysGetRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getStreakCelebration(request, requestOptions));
    }

    private async __getStreakCelebration(
        request: FoodContextProtocolApi.GetStreakCelebrationAgentsStreakStreakDaysGetRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { streak_days: streakDays, user_name: userName } = request;
        const _queryParams: Record<string, unknown> = {
            user_name: userName,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `agents/streak/${core.url.encodePathParam(streakDays)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/agents/streak/{streak_days}");
    }

    /**
     * Get today's food tip based on user preferences.
     *
     * Uses grounding for fresh, relevant tips.
     *
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.getFoodTip()
     */
    public getFoodTip(requestOptions?: AgentsClient.RequestOptions): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getFoodTip(requestOptions));
    }

    private async __getFoodTip(
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/food-tip",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/agents/food-tip");
    }

    /**
     * Get seasonal food recommendations for a location.
     *
     * @param {FoodContextProtocolApi.GetSeasonalReminderAgentsSeasonalReminderGetRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.getSeasonalReminder({
     *         location: "location"
     *     })
     */
    public getSeasonalReminder(
        request: FoodContextProtocolApi.GetSeasonalReminderAgentsSeasonalReminderGetRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getSeasonalReminder(request, requestOptions));
    }

    private async __getSeasonalReminder(
        request: FoodContextProtocolApi.GetSeasonalReminderAgentsSeasonalReminderGetRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { location } = request;
        const _queryParams: Record<string, unknown> = {
            location,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/seasonal-reminder",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/agents/seasonal-reminder");
    }

    /**
     * Process a batch of photos to detect and analyze food.
     *
     * Uses:
     * - Multimodal analysis for food detection
     * - Function calling for structured extraction
     *
     * @param {FoodContextProtocolApi.MediaBatchRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.processMediaBatch({
     *         image_urls: ["image_urls"]
     *     })
     */
    public processMediaBatch(
        request: FoodContextProtocolApi.MediaBatchRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__processMediaBatch(request, requestOptions));
    }

    private async __processMediaBatch(
        request: FoodContextProtocolApi.MediaBatchRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/process-media",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/agents/process-media");
    }

    /**
     * Filter images to identify which contain food.
     *
     * Faster than full analysis - only checks food presence.
     *
     * @param {FoodContextProtocolApi.FilterImagesRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.filterFoodImages({
     *         image_urls: ["image_urls"]
     *     })
     */
    public filterFoodImages(
        request: FoodContextProtocolApi.FilterImagesRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__filterFoodImages(request, requestOptions));
    }

    private async __filterFoodImages(
        request: FoodContextProtocolApi.FilterImagesRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/filter-food-images",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/agents/filter-food-images");
    }

    /**
     * Generate a shareable weekly food digest.
     *
     * Uses extended thinking for creative content generation.
     *
     * @param {FoodContextProtocolApi.GenerateBlogContentAgentsGenerateBlogPostRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.generateBlogContent()
     */
    public generateBlogContent(
        request: FoodContextProtocolApi.GenerateBlogContentAgentsGenerateBlogPostRequest = {},
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__generateBlogContent(request, requestOptions));
    }

    private async __generateBlogContent(
        request: FoodContextProtocolApi.GenerateBlogContentAgentsGenerateBlogPostRequest = {},
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { user_name: userName } = request;
        const _queryParams: Record<string, unknown> = {
            user_name: userName,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/generate-blog",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/agents/generate-blog");
    }

    /**
     * Generate a social media post.
     *
     * @param {FoodContextProtocolApi.SocialPostRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.createSocialPost({
     *         log_id: "log_id"
     *     })
     */
    public createSocialPost(
        request: FoodContextProtocolApi.SocialPostRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__createSocialPost(request, requestOptions));
    }

    private async __createSocialPost(
        request: FoodContextProtocolApi.SocialPostRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/social-post",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/agents/social-post");
    }

    /**
     * Generate a narrative food story from multiple meals.
     *
     * @param {FoodContextProtocolApi.FoodStoryRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.generateFoodStory({
     *         log_ids: ["log_ids"]
     *     })
     */
    public generateFoodStory(
        request: FoodContextProtocolApi.FoodStoryRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__generateFoodStory(request, requestOptions));
    }

    private async __generateFoodStory(
        request: FoodContextProtocolApi.FoodStoryRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/food-story",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/agents/food-story");
    }

    /**
     * Generate a comprehensive monthly food review.
     *
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.generateMonthlyReview()
     */
    public generateMonthlyReview(
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__generateMonthlyReview(requestOptions));
    }

    private async __generateMonthlyReview(
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/monthly-review",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/agents/monthly-review");
    }

    /**
     * Generate a shareable recipe card from a logged meal.
     *
     * @param {FoodContextProtocolApi.RecipeCardRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.agents.generateRecipeCard({
     *         log_id: "log_id"
     *     })
     */
    public generateRecipeCard(
        request: FoodContextProtocolApi.RecipeCardRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__generateRecipeCard(request, requestOptions));
    }

    private async __generateRecipeCard(
        request: FoodContextProtocolApi.RecipeCardRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "agents/recipe-card",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/agents/recipe-card");
    }
}
