// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         draft_id: "draft_id"
 *     }
 */
export interface DeleteDraftPublishDraftsDraftIdDeleteRequest {
    draft_id: string;
}
