// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         content_type: "blog_post"
 *     }
 */
export interface GenerateContentRequest {
    content_type: GenerateContentRequest.ContentType;
    /** Specific log IDs to use for generation */
    log_ids?: string[] | null;
    theme?: string;
    style?: string;
}

export namespace GenerateContentRequest {
    export const ContentType = {
        BlogPost: "blog_post",
        SocialTwitter: "social_twitter",
        SocialInstagram: "social_instagram",
        WeeklyDigest: "weekly_digest",
    } as const;
    export type ContentType = (typeof ContentType)[keyof typeof ContentType];
}
