// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         content_id: "content_id"
 *     }
 */
export interface GetAnalyticsPublishAnalyticsContentIdGetRequest {
    content_id: string;
}
