// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         draft_id: "draft_id"
 *     }
 */
export interface PublishRequest {
    draft_id: string;
    platforms?: PublishRequest.Platforms.Item[];
    publish_immediately?: boolean;
}

export namespace PublishRequest {
    export type Platforms = Platforms.Item[];

    export namespace Platforms {
        export const Item = {
            Blog: "blog",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
