// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         draft_id: "draft_id"
 *     }
 */
export interface UpdateDraftRequest {
    draft_id: string;
    content?: Record<string, unknown> | null;
    status?: UpdateDraftRequest.Status | null;
}

export namespace UpdateDraftRequest {
    export const Status = {
        Draft: "draft",
        Archived: "archived",
        Partial: "partial",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
