// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as FoodContextProtocolApi from "../../../index.js";

export declare namespace MealsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Food log CRUD operations
 */
export class MealsClient {
    protected readonly _options: NormalizedClientOptions<MealsClient.Options>;

    constructor(options: MealsClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Get user's food logs.
     *
     * @param {FoodContextProtocolApi.ListMealsMealsGetRequest} request
     * @param {MealsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.meals.listMeals()
     */
    public listMeals(
        request: FoodContextProtocolApi.ListMealsMealsGetRequest = {},
        requestOptions?: MealsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__listMeals(request, requestOptions));
    }

    private async __listMeals(
        request: FoodContextProtocolApi.ListMealsMealsGetRequest = {},
        requestOptions?: MealsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { limit, days, include_nutrition: includeNutrition } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            days,
            include_nutrition: includeNutrition,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "meals",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/meals");
    }

    /**
     * Add a new meal to the food log. Requires authentication.
     *
     * @param {FoodContextProtocolApi.AddMealRequest} request
     * @param {MealsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.meals.createMeal({
     *         dish_name: "dish_name"
     *     })
     */
    public createMeal(
        request: FoodContextProtocolApi.AddMealRequest,
        requestOptions?: MealsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__createMeal(request, requestOptions));
    }

    private async __createMeal(
        request: FoodContextProtocolApi.AddMealRequest,
        requestOptions?: MealsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "meals",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/meals");
    }

    /**
     * Get a single food log entry.
     *
     * @param {FoodContextProtocolApi.GetSingleMealMealsLogIdGetRequest} request
     * @param {MealsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.meals.getSingleMeal({
     *         log_id: "log_id"
     *     })
     */
    public getSingleMeal(
        request: FoodContextProtocolApi.GetSingleMealMealsLogIdGetRequest,
        requestOptions?: MealsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getSingleMeal(request, requestOptions));
    }

    private async __getSingleMeal(
        request: FoodContextProtocolApi.GetSingleMealMealsLogIdGetRequest,
        requestOptions?: MealsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { log_id: logId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `meals/${core.url.encodePathParam(logId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/meals/{log_id}");
    }

    /**
     * Delete a food log entry. Requires authentication.
     *
     * @param {FoodContextProtocolApi.RemoveMealMealsLogIdDeleteRequest} request
     * @param {MealsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.meals.removeMeal({
     *         log_id: "log_id"
     *     })
     */
    public removeMeal(
        request: FoodContextProtocolApi.RemoveMealMealsLogIdDeleteRequest,
        requestOptions?: MealsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__removeMeal(request, requestOptions));
    }

    private async __removeMeal(
        request: FoodContextProtocolApi.RemoveMealMealsLogIdDeleteRequest,
        requestOptions?: MealsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { log_id: logId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `meals/${core.url.encodePathParam(logId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/meals/{log_id}");
    }

    /**
     * Update a food log entry. Requires authentication.
     *
     * @param {FoodContextProtocolApi.UpdateMealRequest} request
     * @param {MealsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.meals.patchMeal({
     *         log_id: "log_id"
     *     })
     */
    public patchMeal(
        request: FoodContextProtocolApi.UpdateMealRequest,
        requestOptions?: MealsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__patchMeal(request, requestOptions));
    }

    private async __patchMeal(
        request: FoodContextProtocolApi.UpdateMealRequest,
        requestOptions?: MealsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { log_id: logId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `meals/${core.url.encodePathParam(logId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/meals/{log_id}");
    }

    /**
     * Create a meal with image upload.
     *
     * Uploads the image to Firebase Storage, optionally analyzes it with Gemini,
     * and creates the meal record.
     *
     * Args:
     *     image: The food image file (JPEG, PNG, WebP, HEIC supported)
     *     dish_name: Optional dish name (will be inferred from image if not provided)
     *     venue: Optional venue/restaurant name
     *     notes: Optional notes about the meal
     *     auto_analyze: Whether to analyze the image with Gemini (default: True)
     *
     * Returns:
     *     Created meal with log_id and optional analysis results
     *
     * @param {FoodContextProtocolApi.BodyCreateMealWithImageMealsWithImagePost} request
     * @param {MealsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     import { createReadStream } from "fs";
     *     await client.meals.createMealWithImage({
     *         image: fs.createReadStream("/path/to/your/file")
     *     })
     */
    public createMealWithImage(
        request: FoodContextProtocolApi.BodyCreateMealWithImageMealsWithImagePost,
        requestOptions?: MealsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__createMealWithImage(request, requestOptions));
    }

    private async __createMealWithImage(
        request: FoodContextProtocolApi.BodyCreateMealWithImageMealsWithImagePost,
        requestOptions?: MealsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _body = await core.newFormData();
        await _body.appendFile("image", request.image);
        if (request.dish_name != null) {
            _body.append("dish_name", request.dish_name);
        }

        if (request.venue != null) {
            _body.append("venue", request.venue);
        }

        if (request.notes != null) {
            _body.append("notes", request.notes);
        }

        if (request.auto_analyze != null) {
            _body.append("auto_analyze", request.auto_analyze?.toString());
        }

        const _maybeEncodedRequest = await _body.getRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ..._maybeEncodedRequest.headers }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "meals/with-image",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            requestType: "file",
            duplex: _maybeEncodedRequest.duplex,
            body: _maybeEncodedRequest.body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/meals/with-image");
    }
}
