// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface NearbyFoodRequest {
    /** Latitude in degrees */
    latitude?: number | null;
    /** Longitude in degrees */
    longitude?: number | null;
    /** City name or address (e.g., 'San Francisco, CA') */
    location?: string | null;
    /** Search radius in meters */
    radius?: number;
    /** Type of food venue to search for */
    food_type?: NearbyFoodRequest.FoodType;
}

export namespace NearbyFoodRequest {
    /** Type of food venue to search for */
    export const FoodType = {
        Restaurant: "restaurant",
        Cafe: "cafe",
        Bar: "bar",
        Bakery: "bakery",
        MealDelivery: "meal_delivery",
    } as const;
    export type FoodType = (typeof FoodType)[keyof typeof FoodType];
}
