// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as FoodContextProtocolApi from "../../../index.js";

export declare namespace RecipesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Recipe extraction and management
 */
export class RecipesClient {
    protected readonly _options: NormalizedClientOptions<RecipesClient.Options>;

    constructor(options: RecipesClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Convert unstructured recipe text into standard Schema.org/Recipe JSON-LD. Requires authentication.
     *
     * @param {FoodContextProtocolApi.StandardizeRecipeRequest} request
     * @param {RecipesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.recipes.postStandardizeRecipe({
     *         raw_text: "raw_text"
     *     })
     */
    public postStandardizeRecipe(
        request: FoodContextProtocolApi.StandardizeRecipeRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postStandardizeRecipe(request, requestOptions));
    }

    private async __postStandardizeRecipe(
        request: FoodContextProtocolApi.StandardizeRecipeRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "standardize-recipe",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/standardize-recipe");
    }

    /**
     * Scale recipe ingredients to a target number of servings. Requires authentication.
     *
     * @param {FoodContextProtocolApi.ScaleRecipeRequest} request
     * @param {RecipesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.recipes.postScaleRecipe({
     *         recipe_json: {
     *             "key": "value"
     *         },
     *         target_servings: 1
     *     })
     */
    public postScaleRecipe(
        request: FoodContextProtocolApi.ScaleRecipeRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postScaleRecipe(request, requestOptions));
    }

    private async __postScaleRecipe(
        request: FoodContextProtocolApi.ScaleRecipeRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "scaling/scale-recipe",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/scaling/scale-recipe");
    }

    /**
     * Extract a structured recipe from an image, video, or audio file. Requires authentication.
     *
     * @param {FoodContextProtocolApi.MultimodalRecipeRequest} request
     * @param {RecipesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.recipes.postExtractRecipe()
     */
    public postExtractRecipe(
        request: FoodContextProtocolApi.MultimodalRecipeRequest = {},
        requestOptions?: RecipesClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postExtractRecipe(request, requestOptions));
    }

    private async __postExtractRecipe(
        request: FoodContextProtocolApi.MultimodalRecipeRequest = {},
        requestOptions?: RecipesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "recipes/extract",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/recipes/extract");
    }

    /**
     * Generate a recipe from a list of ingredients. Requires authentication.
     *
     * @param {FoodContextProtocolApi.GenerateRecipeRequest} request
     * @param {RecipesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.recipes.postGenerateRecipe({
     *         ingredients: ["ingredients"]
     *     })
     */
    public postGenerateRecipe(
        request: FoodContextProtocolApi.GenerateRecipeRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postGenerateRecipe(request, requestOptions));
    }

    private async __postGenerateRecipe(
        request: FoodContextProtocolApi.GenerateRecipeRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "recipes/generate",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/recipes/generate");
    }

    /**
     * List user's saved recipes.
     *
     * @param {FoodContextProtocolApi.GetRecipesListRecipesGetRequest} request
     * @param {RecipesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.recipes.getRecipesList()
     */
    public getRecipesList(
        request: FoodContextProtocolApi.GetRecipesListRecipesGetRequest = {},
        requestOptions?: RecipesClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getRecipesList(request, requestOptions));
    }

    private async __getRecipesList(
        request: FoodContextProtocolApi.GetRecipesListRecipesGetRequest = {},
        requestOptions?: RecipesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { limit, include_archived: includeArchived, favorites_only: favoritesOnly } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            include_archived: includeArchived,
            favorites_only: favoritesOnly,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "recipes",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/recipes");
    }

    /**
     * Save a new recipe. Requires authentication.
     *
     * @param {FoodContextProtocolApi.SaveRecipeRequest} request
     * @param {RecipesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.recipes.postSaveRecipe({
     *         name: "name",
     *         ingredients: ["ingredients"]
     *     })
     */
    public postSaveRecipe(
        request: FoodContextProtocolApi.SaveRecipeRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postSaveRecipe(request, requestOptions));
    }

    private async __postSaveRecipe(
        request: FoodContextProtocolApi.SaveRecipeRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "recipes",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/recipes");
    }

    /**
     * Get a single recipe by ID.
     *
     * @param {FoodContextProtocolApi.GetRecipeByIdRecipesRecipeIdGetRequest} request
     * @param {RecipesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.recipes.getRecipeById({
     *         recipe_id: "recipe_id"
     *     })
     */
    public getRecipeById(
        request: FoodContextProtocolApi.GetRecipeByIdRecipesRecipeIdGetRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getRecipeById(request, requestOptions));
    }

    private async __getRecipeById(
        request: FoodContextProtocolApi.GetRecipeByIdRecipesRecipeIdGetRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { recipe_id: recipeId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `recipes/${core.url.encodePathParam(recipeId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/recipes/{recipe_id}");
    }

    /**
     * Permanently delete a recipe. Requires authentication.
     *
     * @param {FoodContextProtocolApi.DeleteRecipeByIdRecipesRecipeIdDeleteRequest} request
     * @param {RecipesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.recipes.deleteRecipeById({
     *         recipe_id: "recipe_id"
     *     })
     */
    public deleteRecipeById(
        request: FoodContextProtocolApi.DeleteRecipeByIdRecipesRecipeIdDeleteRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__deleteRecipeById(request, requestOptions));
    }

    private async __deleteRecipeById(
        request: FoodContextProtocolApi.DeleteRecipeByIdRecipesRecipeIdDeleteRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { recipe_id: recipeId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `recipes/${core.url.encodePathParam(recipeId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/recipes/{recipe_id}");
    }

    /**
     * Update a recipe. Requires authentication.
     *
     * @param {FoodContextProtocolApi.UpdateRecipeRequest} request
     * @param {RecipesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.recipes.patchRecipe({
     *         recipe_id: "recipe_id"
     *     })
     */
    public patchRecipe(
        request: FoodContextProtocolApi.UpdateRecipeRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__patchRecipe(request, requestOptions));
    }

    private async __patchRecipe(
        request: FoodContextProtocolApi.UpdateRecipeRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { recipe_id: recipeId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `recipes/${core.url.encodePathParam(recipeId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/recipes/{recipe_id}");
    }

    /**
     * Toggle favorite status on a recipe. Requires authentication.
     *
     * @param {FoodContextProtocolApi.FavoriteRecipeRequest} request
     * @param {RecipesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.recipes.postFavoriteRecipe({
     *         recipe_id: "recipe_id"
     *     })
     */
    public postFavoriteRecipe(
        request: FoodContextProtocolApi.FavoriteRecipeRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postFavoriteRecipe(request, requestOptions));
    }

    private async __postFavoriteRecipe(
        request: FoodContextProtocolApi.FavoriteRecipeRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { recipe_id: recipeId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `recipes/${core.url.encodePathParam(recipeId)}/favorite`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/recipes/{recipe_id}/favorite",
        );
    }

    /**
     * Archive a recipe (soft delete). Requires authentication.
     *
     * @param {FoodContextProtocolApi.PostArchiveRecipeRecipesRecipeIdArchivePostRequest} request
     * @param {RecipesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.recipes.postArchiveRecipe({
     *         recipe_id: "recipe_id"
     *     })
     */
    public postArchiveRecipe(
        request: FoodContextProtocolApi.PostArchiveRecipeRecipesRecipeIdArchivePostRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__postArchiveRecipe(request, requestOptions));
    }

    private async __postArchiveRecipe(
        request: FoodContextProtocolApi.PostArchiveRecipeRecipesRecipeIdArchivePostRequest,
        requestOptions?: RecipesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { recipe_id: recipeId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `recipes/${core.url.encodePathParam(recipeId)}/archive`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/recipes/{recipe_id}/archive");
    }
}
