// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         period1_start: "period1_start",
 *         period1_end: "period1_end",
 *         period2_start: "period2_start",
 *         period2_end: "period2_end"
 *     }
 */
export interface ComparePeriodsRequest {
    period1_start: string;
    period1_end: string;
    period2_start: string;
    period2_end: string;
}
