// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as FoodContextProtocolApi from "../../../index.js";

export declare namespace PublishingClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Recipe and content publishing
 */
export class PublishingClient {
    protected readonly _options: NormalizedClientOptions<PublishingClient.Options>;

    constructor(options: PublishingClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Generate content from food logs.
     *
     * Supports:
     * - blog_post: SEO-optimized blog post
     * - social_twitter: Twitter-optimized post
     * - social_instagram: Instagram-optimized post
     * - weekly_digest: Weekly food journey summary
     *
     * @param {FoodContextProtocolApi.GenerateContentRequest} request
     * @param {PublishingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.publishing.generateContent({
     *         content_type: "blog_post"
     *     })
     */
    public generateContent(
        request: FoodContextProtocolApi.GenerateContentRequest,
        requestOptions?: PublishingClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__generateContent(request, requestOptions));
    }

    private async __generateContent(
        request: FoodContextProtocolApi.GenerateContentRequest,
        requestOptions?: PublishingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "publish/generate",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/publish/generate");
    }

    /**
     * List all content drafts.
     *
     * @param {PublishingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.publishing.listDrafts()
     */
    public listDrafts(
        requestOptions?: PublishingClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__listDrafts(requestOptions));
    }

    private async __listDrafts(
        requestOptions?: PublishingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "publish/drafts",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/publish/drafts");
    }

    /**
     * Get a specific draft.
     *
     * @param {FoodContextProtocolApi.GetDraftPublishDraftsDraftIdGetRequest} request
     * @param {PublishingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.publishing.getDraft({
     *         draft_id: "draft_id"
     *     })
     */
    public getDraft(
        request: FoodContextProtocolApi.GetDraftPublishDraftsDraftIdGetRequest,
        requestOptions?: PublishingClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getDraft(request, requestOptions));
    }

    private async __getDraft(
        request: FoodContextProtocolApi.GetDraftPublishDraftsDraftIdGetRequest,
        requestOptions?: PublishingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { draft_id: draftId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `publish/drafts/${core.url.encodePathParam(draftId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/publish/drafts/{draft_id}");
    }

    /**
     * Delete a draft.
     *
     * @param {FoodContextProtocolApi.DeleteDraftPublishDraftsDraftIdDeleteRequest} request
     * @param {PublishingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.publishing.deleteDraft({
     *         draft_id: "draft_id"
     *     })
     */
    public deleteDraft(
        request: FoodContextProtocolApi.DeleteDraftPublishDraftsDraftIdDeleteRequest,
        requestOptions?: PublishingClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__deleteDraft(request, requestOptions));
    }

    private async __deleteDraft(
        request: FoodContextProtocolApi.DeleteDraftPublishDraftsDraftIdDeleteRequest,
        requestOptions?: PublishingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { draft_id: draftId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `publish/drafts/${core.url.encodePathParam(draftId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/publish/drafts/{draft_id}");
    }

    /**
     * Update a draft's content or status.
     *
     * @param {FoodContextProtocolApi.UpdateDraftRequest} request
     * @param {PublishingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.publishing.updateDraft({
     *         draft_id: "draft_id"
     *     })
     */
    public updateDraft(
        request: FoodContextProtocolApi.UpdateDraftRequest,
        requestOptions?: PublishingClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__updateDraft(request, requestOptions));
    }

    private async __updateDraft(
        request: FoodContextProtocolApi.UpdateDraftRequest,
        requestOptions?: PublishingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { draft_id: draftId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `publish/drafts/${core.url.encodePathParam(draftId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/publish/drafts/{draft_id}");
    }

    /**
     * Publish a draft to configured platforms.
     *
     * Currently supports:
     * - blog: Publish to Astro CMS (requires ASTRO_API_KEY and ASTRO_ENDPOINT)
     *
     * @param {FoodContextProtocolApi.PublishRequest} request
     * @param {PublishingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.publishing.publishDraft({
     *         draft_id: "draft_id"
     *     })
     */
    public publishDraft(
        request: FoodContextProtocolApi.PublishRequest,
        requestOptions?: PublishingClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__publishDraft(request, requestOptions));
    }

    private async __publishDraft(
        request: FoodContextProtocolApi.PublishRequest,
        requestOptions?: PublishingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { draft_id: draftId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `publish/drafts/${core.url.encodePathParam(draftId)}/publish`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/publish/drafts/{draft_id}/publish",
        );
    }

    /**
     * List all published content.
     *
     * @param {PublishingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.publishing.listPublished()
     */
    public listPublished(
        requestOptions?: PublishingClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__listPublished(requestOptions));
    }

    private async __listPublished(
        requestOptions?: PublishingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "publish/published",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/publish/published");
    }

    /**
     * Get analytics for published content.
     *
     * Fetches analytics from Astro CMS if configured.
     *
     * @param {FoodContextProtocolApi.GetAnalyticsPublishAnalyticsContentIdGetRequest} request
     * @param {PublishingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FoodContextProtocolApi.UnprocessableEntityError}
     *
     * @example
     *     await client.publishing.getAnalytics({
     *         content_id: "content_id"
     *     })
     */
    public getAnalytics(
        request: FoodContextProtocolApi.GetAnalyticsPublishAnalyticsContentIdGetRequest,
        requestOptions?: PublishingClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getAnalytics(request, requestOptions));
    }

    private async __getAnalytics(
        request: FoodContextProtocolApi.GetAnalyticsPublishAnalyticsContentIdGetRequest,
        requestOptions?: PublishingClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { content_id: contentId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `publish/analytics/${core.url.encodePathParam(contentId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FoodContextProtocolApi.UnprocessableEntityError(
                        _response.error.body as FoodContextProtocolApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FoodContextProtocolApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/publish/analytics/{content_id}",
        );
    }
}
