// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         food1: "food1",
 *         food2: "food2"
 *     }
 */
export interface CompareKnowledgeCompareGetRequest {
    /** First food to compare */
    food1: string;
    /** Second food to compare */
    food2: string;
}
