// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         log_id: "log_id"
 *     }
 */
export interface FcpRoutesKnowledgeEnrichRequest {
    log_id: string;
    include_sustainability?: boolean;
    include_micronutrients?: boolean;
}
