// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         items: [{
 *                 "key": "value"
 *             }]
 *     }
 */
export interface AddFromReceiptRequest {
    items: Record<string, unknown>[];
    purchase_date?: string | null;
    default_storage?: string;
}
