// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         image_url: "image_url"
 *     }
 */
export interface ParseReceiptRequest {
    image_url: string;
    store_hint?: string | null;
}
