// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         audio_url: "audio_url"
 *     }
 */
export interface AudioLogRequest {
    audio_url: string;
    notes?: string | null;
}
