// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         product_name: "product_name",
 *         ingredients: ["ingredients"]
 *     }
 */
export interface CottageLabelRequest {
    product_name: string;
    ingredients: string[];
    net_weight?: string | null;
    business_name?: string | null;
    business_address?: string | null;
    is_refrigerated?: boolean;
}
