// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         dish_name: "dish_name",
 *         ingredients: ["ingredients"],
 *         user_allergies: ["user_allergies"],
 *         user_diet: ["user_diet"]
 *     }
 */
export interface DietaryCheckRequest {
    dish_name: string;
    ingredients: string[];
    user_allergies: string[];
    user_diet: string[];
}
