// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         neighborhood: "neighborhood",
 *         existing_cuisines: ["existing_cuisines"]
 *     }
 */
export interface EconomicGapRequest {
    neighborhood: string;
    existing_cuisines: string[];
}
