// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         city_name: "city_name",
 *         theme: "theme"
 *     }
 */
export interface FoodFestivalRequest {
    city_name: string;
    theme: string;
    target_vendor_count?: number;
    location_description?: string | null;
}
