// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         subject: "subject"
 *     }
 */
export interface GetPairingsFlavorPairingsGetRequest {
    subject: string;
    pairing_type?: string;
}
