// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetTrendsTrendsIdentifyGetRequest {
    region?: string;
    cuisine_focus?: string | null;
}
