// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         subject: "subject"
 *     }
 */
export interface ImagePromptRequest {
    subject: string;
    style?: string;
    context?: string;
}
