// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         transcript: "transcript"
 *     }
 */
export interface VoiceTranscriptRequest {
    transcript: string;
}
