// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         voice_input: "voice_input"
 *     }
 */
export interface VoiceCorrectionRequest {
    voice_input: string;
}
