// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetLifetimeProfileProfileLifetimeGetRequest {
    /** Page number (1-indexed) */
    page?: number;
    /** Items per page */
    page_size?: number;
    /** Bypass cache and re-analyze */
    refresh?: boolean;
}
