// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         audio_base64: "audio_base64"
 *     }
 */
export interface VoiceMealLogRequest {
    /** Base64-encoded audio data */
    audio_base64: string;
    /** Audio MIME type (audio/pcm, audio/webm, audio/wav) */
    mime_type?: string;
    /** Sample rate in Hz */
    sample_rate?: number;
}
