// This file was auto-generated by Fern from our API Definition.

import type * as FoodContextProtocolApi from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             image_url: "image_url"
 *         }
 *     }
 */
export interface AnalyzeImageWithThinkingAnalyzeThinkingPostRequest {
    thinking_level?: string;
    body: FoodContextProtocolApi.ImageUrlRequest;
}
