// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         event_title: "event_title",
 *         start_time: "start_time"
 *     }
 */
export interface CalendarSyncRequest {
    event_title: string;
    start_time: string;
    description?: string | null;
}
