// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         filename: "filename",
 *         content: "content"
 *     }
 */
export interface DriveSaveRequest {
    filename: string;
    content: string;
    folder?: string;
}
