// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         action: "action"
 *     }
 */
export interface CookingClipRequest {
    /** Cooking action (e.g., 'chopping vegetables') */
    action: string;
    /** Optional list of ingredients being used */
    ingredients?: string[] | null;
    /** Video length (4-8 seconds) */
    duration_seconds?: number;
    /** Max wait time in seconds */
    timeout_seconds?: number;
}
