// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         topic: "topic"
 *     }
 */
export interface ResearchRequest {
    /** Research topic */
    topic: string;
    /** Optional user context (dietary restrictions, goals) */
    context?: string | null;
    /** Max wait time in seconds */
    timeout_seconds?: number;
}
