// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ingredients: ["ingredients"]
 *     }
 */
export interface DeductRequest {
    ingredients: string[];
    servings?: number;
}
