// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         item_id: "item_id"
 *     }
 */
export interface DeletePantryItemRouteInventoryPantryItemIdDeleteRequest {
    item_id: string;
}
