// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         item_id: "item_id"
 *     }
 */
export interface UpdatePantryItemRequest {
    item_id: string;
    name?: string | null;
    quantity?: number | null;
    unit?: string | null;
    expiration_date?: string | null;
}
