// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         job_type: "job_type"
 *     }
 */
export interface ScheduleUpdateRequest {
    job_type: string;
    enabled?: boolean;
    hour?: number | null;
    minute?: number | null;
    day_of_week?: string | null;
    day_of_month?: number | null;
}
