// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         job_type: "job_type"
 *     }
 */
export interface TriggerJobManuallySchedulerTriggerJobTypePostRequest {
    job_type: string;
}
