// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         food_items: ["food_items"],
 *         allergies: ["allergies"]
 *     }
 */
export interface AllergenAlertsRequest {
    food_items: string[];
    allergies: string[];
    user_id?: string | null;
}
