// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         food_items: ["food_items"],
 *         medications: ["medications"]
 *     }
 */
export interface DrugInteractionsRequest {
    food_items: string[];
    medications: string[];
    user_id?: string | null;
}
