// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         food_name: "food_name",
 *         allergens: "allergens"
 *     }
 */
export interface GetAllergenAlertsSafetyAllergensGetRequest {
    food_name: string;
    allergens: string;
}
