// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         food_name: "food_name",
 *         medications: "medications"
 *     }
 */
export interface GetDrugInteractionsSafetyDrugInteractionsGetRequest {
    food_name: string;
    medications: string;
}
