// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         food_name: "food_name"
 *     }
 */
export interface GetFoodRecallsSafetyRecallsGetRequest {
    food_name: string;
}
