// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         restaurant_name: "restaurant_name"
 *     }
 */
export interface GetRestaurantInfoSafetyRestaurantRestaurantNameGetRequest {
    restaurant_name: string;
    location?: string | null;
}
