// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         location: "location"
 *     }
 */
export interface GetSeasonalSafetySafetySeasonalGetRequest {
    location: string;
}
