// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         claim: "claim",
 *         food_name: "food_name"
 *     }
 */
export interface NutritionClaimRequest {
    claim: string;
    food_name: string;
}
