// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         food_items: ["food_items"]
 *     }
 */
export interface RecallsRequest {
    food_items: string[];
    user_id?: string | null;
}
